spring:
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
debug: true
server:
  port : 8081
oauth:
  url: http://localhost:8080
  token-url: ${oauth.url}/oauth2/token
  api-client-id: api-client-id
  api-client-secret: api123
  jwts:
    - issuer-url : https://accounts.google.com
      jwks-url : https://www.googleapis.com/oauth2/v3/certs