CREATE TABLE USER_DETAIL (
   ID BIGSERIAL PRIMARY KEY,
   USER_ID VARCHAR(100) NOT NULL,
   USER_NAME VARCHAR(255) NOT NULL,
   PROVIDER VARCHAR(50) NOT NULL,
   PASSWORD VARCHAR(255),
   CREATED_TIME TIMESTAMP NOT NULL default localtimestamp,
   CREATED_BY VARCHAR(255) NOT NULL default 'system',
   UPDATED_TIME TIMESTAMP,
   UPDATED_BY VARCHAR(255),
   UNIQUE (USER_ID),
   UNIQUE (USER_NAME, PROVIDER)
);